name: Setup project
description: Set up Node.js, pnpm, and install dependencies

runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v5

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: lts/*

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
